
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: devop-tools
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080